package com.example.passwordmanagerv1.utils

const val DATAFILE_NAME = "accounts"
const val DATAFILE_EXTENSION = ".data"
const val DATAFILE_NAME_AND_EXTENSION = DATAFILE_NAME + DATAFILE_EXTENSION
const val DATAFILE_MIMETYPE_BINARY = "application/octet-stream"
const val DATAFILE_MIMETYPE_PLAIN = "text/plain"

const val DEBUG_PASSWORD = "debug"

// According to https://owasp.org/www-community/password-special-characters
const val VALID_SPECIAL_CHARS_WITHOUT_SPACE = "!\"#\$%&'()*+,-./:;<=>?@[\\]^_`{|}~"
const val VALID_SPECIAL_CHARS_WITH_SPACE = " !\"#\$%&'()*+,-./:;<=>?@[\\]^_`{|}~"
const val ALPHANUMERIC_CHARS = "qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM1234567890"

const val OPTION_CODE_ADD_ACCOUNT = "ADD_ACCOUNT"
const val OPTION_CODE_SEARCH_ACCOUNT_NAME = "SEARCH_ACCOUNT_NAME"
const val OPTION_CODE_SEARCH_EMAIL = "SEARCH_EMAIL"
const val OPTION_CODE_SEARCH_USERNAME = "SEARCH_USERNAME"
const val OPTION_CODE_SEARCH_PHONE = "SEARCH_PHONE"
const val OPTION_CODE_SEARCH_PASSWORD = "SEARCH_PASSWORD"
const val OPTION_CODE_SEARCH_LINKED_ACCOUNT = "SEARCH_LINKED_ACCOUNT"
const val OPTION_CODE_IMPORT_EXPORT_DATA = "IMPORT_EXPORT_DATA"

val MENU_OPTION_ORDER = listOf(
    OPTION_CODE_ADD_ACCOUNT,
    OPTION_CODE_SEARCH_ACCOUNT_NAME,
    OPTION_CODE_SEARCH_EMAIL,
    OPTION_CODE_SEARCH_USERNAME,
    OPTION_CODE_SEARCH_PHONE,
    OPTION_CODE_SEARCH_PASSWORD,
    OPTION_CODE_SEARCH_LINKED_ACCOUNT,
    OPTION_CODE_IMPORT_EXPORT_DATA
)

enum class AccountFieldType {
    accountName,
    email,
    username,
    phone,
    password,
    linkedAccounts,
    misc
}

const val EXTRA_ACCOUNT_NAME = "EXTRA_ACCOUNT_NAME"
const val EXTRA_ACCOUNT_FIELD_TYPE = "EXTRA_ACCOUNT_FIELD"
const val EXTRA_ACCOUNT_FIELD_VALUE = "EXTRA_ACCOUNT_FIELD_VALUE"
const val EXTRA_MISC_FIELD_TITLE = "EXTRA_MISC_FIELD_TITLE"
const val EXTRA_IMPORT_DATA_URI = "EXTRA_IS_IMPORTING_DATA"

const val LABEL_COPY = "LABEL_COPY"

const val KEY_ALGORITHM = "PBKDF2WithHmacSHA256"
const val KEY_SALT = "69420"
const val DERIVED_KEY_LENGTH = 256
const val KEY_ITERATIONS = 69420